#!/bin/sh
# vim: ts=4 sw=4 et

usage="beamer_psnup [1|3|4|7|8] dir basename"

if test $# != 3
then
    echo "${usage}"
    exit 1
fi

n=$1
dir=$2
basename=$3

mundula_scales=true

case "${n}" in
    1)
        if ${mundula_scales}
        then
            scale=1.96

            ht0=90
            wid0=550

            page0="0L@${scale}(${wid0},${ht0})"

            transform="1:${page0}"
        else
            scale=1

            ht0=0
            wid0=0

            page0="0L@${scale}(${wid0},${ht0})"

            transform="1:${page0}"
        fi
        ;;
    3|4)
        if ${mundula_scales}
        then
            scale=1.0

            ht0=50
            ht1=440

            wid0=290
            wid1=570

            page0="0L@${scale}(${wid0},${ht0})"
            page1="1L@${scale}(${wid0},${ht1})"
            page2="2L@${scale}(${wid1},${ht0})"
            page3="3L@${scale}(${wid1},${ht1})"

            case "${n}" in
                3)
                    transform="3:${page0}+${page1}+${page2}"
                    ;;
                4)
                    transform="4:${page0}+${page1}+${page2}+${page3}"
                    ;;
            esac
        else
            scale=0.49

            ht0=0
            ht1=138

            wid0=0
            wid1=187

            page0="0@${scale}(${wid0},${ht1})"
            page1="1@${scale}(${wid1},${ht1})"
            page2="2@${scale}(${wid0},${ht0})"
            page3="3@${scale}(${wid1},${ht0})"

            case "${n}" in
                3)
                    transform="3:${page0}+${page1}+${page2}"
                    ;;
                4)
                    transform="4:${page0}+${page1}+${page2}+${page3}"
                    ;;
            esac
        fi
        ;;
    7|8)
        if ${mundula_scales}
        then
            scale=0.70

            wid0=30
            wid1=300

            ht0=620
            ht1=425
            ht2=230
            ht3=035

            page0="0@${scale}(${wid0},${ht0})"
            page1="1@${scale}(${wid1},${ht0})"
            page2="2@${scale}(${wid0},${ht1})"
            page3="3@${scale}(${wid1},${ht1})"
            page4="4@${scale}(${wid0},${ht2})"
            page5="5@${scale}(${wid1},${ht2})"
            page6="6@${scale}(${wid0},${ht3})"
            page7="7@${scale}(${wid1},${ht3})"

            case "${n}" in
                7)
                    transform="7:${page0}+${page1}+${page2}+${page3}"
                    transform="${transform}+${page4}+${page5}+${page6}"
                    ;;
                8)
                    transform="8:${page0}+${page1}+${page2}+${page3}"
                    transform="${transform}+${page4}+${page5}+${page6}+${page7}"
                    ;;
            esac
        else
            scale=0.32

            ht0=10
            ht1=148

            wid0=89
            wid1=179
            wid2=269
            wid3=359

            page0="0L@${scale}(${wid0},${ht0})"
            page1="1L@${scale}(${wid0},${ht1})"
            page2="2L@${scale}(${wid1},${ht0})"
            page3="3L@${scale}(${wid1},${ht1})"
            page4="4L@${scale}(${wid2},${ht0})"
            page5="5L@${scale}(${wid2},${ht1})"
            page6="6L@${scale}(${wid3},${ht0})"
            page7="7L@${scale}(${wid3},${ht1})"

            case "${n}" in
                7)
                    transform="7:${page0}+${page1}+${page2}+${page3}"
                    transform="${transform}+${page4}+${page5}+${page6}"
                    ;;
                8)
                    transform="8:${page0}+${page1}+${page2}+${page3}"
                    transform="${transform}+${page4}+${page5}+${page6}+${page7}"
                    ;;
            esac
        fi
        ;;
    *)
        echo "${usage}"
        exit 1
        ;;
esac

input_filename=".${dir}/${basename}.ps"
output_filename="${dir}/${basename}.${n}.ps"
error_filename=".${dir}/.psnup${n}.${basename}.out"

pstops -q -w21cm -h29.7cm ${transform} \
    ${input_filename} ${output_filename} 2> ${error_filename}
status=$?

if test ${status} != 0
then
    cat ${error_filename}
fi

exit ${status}
